### ISSUE TITLE
Exception while delete shop - UninstallEvent

### ISSUE THREAD

**Issue by piotrooo** [dreamcommerce/appstore-bundle#2]
When `UninstallEvent` is triggered Postgres returns error:

```
LOG:  statement: BEGIN
LOG:  execute <unnamed>: DELETE FROM shops WHERE id = $1
DETAIL:  parameters: $1 = '1'
ERROR:  update or delete on table "shops" violates foreign key constraint "fk_aa5a118e4d16c4dd" on table "tokens"
DETAIL:  Key (id)=(1) is still referenced from table "tokens".
STATEMENT:  DELETE FROM shops WHERE id = $1
LOG:  statement: ROLLBACK
```

When shop is deleted all its references should be deleted.

**Comment by er1z** [comment]
All references are completely up to you. Bundle tells Doctrine to delete an entity calling a mapped interface. But how you do setup cascading on Shop entity - it's completely up to you.
